name: Docker Image CI # Actions名称

on: [push] # 执行时机

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install
        run: yarn

      - name: build project
        run: yarn run build

      - name: Build the Docker image
        run: |
          docker login --username=${{ secrets.DOCKER_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password=${{ secrets.DOCKER_PASSWORD }}
          docker build -t react-app:latest . 
          docker tag react-app registry.cn-hangzhou.aliyuncs.com/lvxiaowu/react-app:latest
          docker push registry.cn-hangzhou.aliyuncs.com/lvxiaowu/react-app:latest
      - name: ssh docker login
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: cd ~ &&  sh pwd.sh ${{ secrets.DOCKER_PASSWORD }} && sh react-app-deploy.sh ${{ secrets.DOCKER_USERNAME }}
